

FROM python:3.11-slim AS base

WORKDIR /todo

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

FROM base AS development

COPY . .

WORKDIR /

CMD ["uvicorn", "todo.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

FROM base AS production

COPY . .

WORKDIR /

CMD ["uvicorn", "todo.main:app", "--host", "0.0.0.0", "--port", "80"]

EXPOSE 80

